tables:
  - table_name: wikipedia
    fields:
      __time: TimeField
      channel: StringField
      comment: StringField
      commentLength: NumberField
  - table_name: cars
    fields:
      color: StringField
      make: StringField
      price: NumberField
      sold: TimeField
db_settings:
#  - name: pg_test
#    tables:
#      - sale
#    db_type: PG
#    host: localhost
#    port: '5432'
#    user: postgres
#    password: '12345'
#    db_name: test
#    black_tables: []
#    black_fields:
#      sale: ['']
  - name: druid_test
    tables:
      - wikipedia
    db_type: DRUID
    host: localhost
    port: '8888'
    black_tables: []
    black_fields:
      blacktable_1:
        - test1
        - test2
  - name: es_test
    tables:
      - cars
    db_type: ES
    host: localhost
    port: "9200"
    black_tables: []
    black_fields:
      blacktable_1:
        - test1
        - test2