tables:
  - table_name: table1
    fields:
      username: StringField
      password: IntField
  - table_name: table2
    fields:
      username: StringField
      password: IntField
  - table_name: model1_testuser
    fields:
      username: StringField
      password: StringField
      datetime: TimeField
db_settings:
  - name: pg_test
    tables:
      - sale
    db_type: PG
    host: localhost
    port: '5432'
    user: postgres
    password: '12345'
    db_name: test
    black_tables: []
    black_fields:
      sale: ['']
  - name: druid_test
    tables:
      - wikipedia
    db_type: DRUID
    host: localhost
    port: '8888'
    user: postgres
    password: '12345'
    db_name: test
    black_tables: []
    black_fields:
      a:
        - test1
        - test2