tables:
  - table_name: table1
    fields:
      username: StringField
      password: IntField
  - table_name: wikipedia
    fields:
      comment: StringField
      countryName: IntField
  - table_name: table2
    fields:
      username: StringField
      password: IntField
  - table_name: model1_testuser
    fields:
      username: StringField
      password: StringField
      datetime: TimeField
  - table_name: cars
    fields:
      make: StringField
  - table_name: people
    fields:
      username: StringField
      age: IntField
      logintime: TimeField
db_settings:
#  - name: pg_test
#    tables:
#      - sale
#    db_type: PG
#    host: localhost
#    port: '5432'
#    user: postgres
#    password: '12345'
#    db_name: test
#    black_tables: []
#    black_fields:
#      sale: ['']
  - name: RestSQL
    tables:
      - wikipedia
    db_type: DRUID
    host: localhost
    port: '8888'
    user: postgres
    password: '12345'
    db_name: test
    black_tables: []
    black_fields:
      blacktable_1:
        - test1
        - test2
  - name: es_test
    tables:
      - cars
    db_type: ES
    host: localhost
    port: "9200"
    black_tables: []
    black_fields:
      blacktable_1:
        - test1
        - test2
  - name: pg_test
    tables:
      - people
    db_type: PG
    host: localhost
    port: "5432"
    user: postgres
    db_name: testdjango
    password: zhang23785491
    schema: public



